linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - gocritic
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  gosec:
    excludes:
      - G104 # allow unhandled errors in deferred calls

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
